'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { ArrowUpRight, ArrowLeft, ArrowRight, Pause, Play, Heart, Plus } from 'lucide-react';
import { Product } from '@/lib/types';
import { money } from '@/lib/utils';
import { useStore } from './store';
const slides = [
    { label: 'THE WATCH EDIT / 2026', lines: ['MAKE EVERY', 'SECOND', 'SIGNATURE.'], text: 'Quiet confidence. Lasting impressions. Discover timepieces that say more, without saying a word.', image: '/images/watch.jpg', href: '/shop/watches', cta: 'Explore watches', note: '01 / PRECISION MEETS PERSONALITY', kind: 'watch' },
    { label: 'THE SHOE EDIT / 2026', lines: ['STEP INTO', 'YOUR OWN', 'RHYTHM.'], text: 'Fresh perspectives start from the ground up. Find your everyday signature in our footwear collection.', image: '/images/1549298916-b41d501d3772.jpg', href: '/shop/shoes', cta: 'Explore shoes', note: '02 / FIND YOUR STRIDE', kind: 'shoe' }
];
export function Hero() { const [index, setIndex] = useState(0); const [paused, setPaused] = useState(false); useEffect(() => { if (paused || matchMedia('(prefers-reduced-motion: reduce)').matches)
    return; const t = setInterval(() => setIndex(i => (i + 1) % 2), 6500); return () => clearInterval(t); }, [paused]); const s = slides[index]; return <section className={`hero hero-${s.kind}`} aria-roledescription="carousel" aria-label="Featured collections" onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)}><div className="hero-glow" aria-hidden="true"/><div className="hero-object" key={s.image}><Image src={s.image} alt={index === 0 ? 'Minimal watch with a refined leather strap' : 'Amber everyday sneakers'} fill priority sizes="(max-width: 700px) 100vw, 66vw"/></div><div className="hero-copy" key={s.label}><p className="eyebrow"><span className="gold-line"/>{s.label}</p><h1 aria-label={s.lines.join(' ')}>{s.lines.map((line, lineIndex) => <span className={lineIndex === 2 ? 'accent-line' : ''} style={{ '--line': lineIndex } as React.CSSProperties} key={line}>{line}</span>)}</h1><p className="hero-description">{s.text}</p><Link className="button gold" href={s.href}>{s.cta}<ArrowUpRight size={18}/></Link><div className="hero-foot"><span>CURATED WITH INTENTION.<br />WORN WITH CONFIDENCE.</span><span className="edition">EST. 2026</span></div></div><span className="vertical-label">THE ART OF EVERYDAY STYLE</span><div className="hero-footer"><div className="hero-caption"><span>{s.note}</span><ArrowUpRight size={20}/></div><div className="hero-controls"><button aria-label="Previous slide" onClick={() => setIndex((index + 1) % 2)}><ArrowLeft size={17}/></button><span>0{index + 1}<i> / 02</i></span><button aria-label="Next slide" onClick={() => setIndex((index + 1) % 2)}><ArrowRight size={17}/></button><button aria-label={paused ? 'Play slideshow' : 'Pause slideshow'} onClick={() => setPaused(!paused)}>{paused ? <Play size={14}/> : <Pause size={14}/>}</button></div></div></section>; }
export function ProductCard({ product: p }: {
    product: Product;
}) { const { wishlist, wish, add } = useStore(); return <article className="product-card"><div className="product-image"><Link href={`/product/${p.slug}`}><Image src={p.primary_image} alt={p.name} fill sizes="(max-width:700px) 50vw, 25vw"/></Link><span className="badge">{p.new_arrival ? 'NEW ARRIVAL' : p.compare_at_price ? 'THE EDIT' : 'ESSENTIAL'}</span><button className={'wish ' + (wishlist.includes(p.id) ? 'selected' : '')} aria-label={`Wishlist ${p.name}`} aria-pressed={wishlist.includes(p.id)} onClick={() => wish(p.id)}><Heart size={17}/></button>{p.category === 'shoes' ? <Link className="quick-add" href={`/product/${p.slug}`}>Choose your size <Plus size={16}/></Link> : <button className="quick-add" disabled={!p.variants.some(v => v.stock > 0)} onClick={() => { const v = p.variants.find(v => v.stock > 0); if (v)
    add(p, v); }}>Add to bag <Plus size={16}/></button>}</div><div className="product-meta"><span>{p.brand} / {p.category}</span><span>{p.variants[0]?.color}</span></div><Link href={`/product/${p.slug}`}><h3>{p.name}</h3></Link><p className="price">{money(p.base_price)} {p.compare_at_price && <del>{money(p.compare_at_price)}</del>}</p></article>; }
export function ProductGrid({ products }: {
    products: Product[];
}) { return <div className="product-grid">{products.map(p => <ProductCard key={p.id} product={p}/>)}</div>; }
export function Featured({ products }: {
    products: Product[];
}) { const [filter, setFilter] = useState('All'); return <section className="section"><div className="section-heading"><div><p className="eyebrow">THE CONSIDERED COLLECTION</p><h2>Your next everyday favourite.</h2></div><Link className="text-link" href="/shop">Shop the collection <ArrowUpRight size={17}/></Link></div><div className="tabs">{['All', 'Watches', 'Shoes'].map(x => <button key={x} className={filter === x ? 'active' : ''} onClick={() => setFilter(x)}>{x}</button>)}</div><ProductGrid products={products.filter(p => filter === 'All' || p.category === filter.toLowerCase()).slice(0, 4)}/></section>; }
